#!/bin/bash

APP_NAME=$1
APP_NAME=${APP_NAME:=parking-app}

VERSION=$2
VERSION=${VERSION:=1.0}

CHANNEL=$3
CHANNEL=${CHANNEL:=mychannel}

CHAINCODE_GOPATH=github.com/${APP_NAME}

HYPERLADGER_ORDERER_SERVER=orderer.example.com:7050

DEPLOY_COMMAND=upgrade
if [ "$VERSION" = "1.0" ]; then
	DEPLOY_COMMAND=instantiate
fi

# cp -v ~/loputoo/hyperledger-fabric-case-study-proto/parking-app/chaincode/parking-app/parking-app-chaincode.go ../chaincode/parking-app/

echo '#############################################'
echo '####### STARTING APP ########################'
echo '#############################################'

echo '####### LOAD CHAINCODE ######################'
docker exec -e "CORE_PEER_LOCALMSPID=Org1MSP" -e "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp" cli peer chaincode install -n $APP_NAME -v $VERSION -p $CHAINCODE_GOPATH

echo '####### INITIANITE CHAINCODE ################'

docker exec -e "CORE_PEER_LOCALMSPID=Org1MSP" -e "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp" cli peer chaincode $DEPLOY_COMMAND -o $HYPERLADGER_ORDERER_SERVER -C $CHANNEL -n $APP_NAME -v $VERSION -c '{"Args":[""]}' -P "OR ('Org1MSP.member','Org2MSP.member')"
sleep 10

echo '####### INVOKE LOAD TO DB ###################'

docker exec -e "CORE_PEER_LOCALMSPID=Org1MSP" -e "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp" cli peer chaincode invoke -o $HYPERLADGER_ORDERER_SERVER -C $CHANNEL -n $APP_NAME -c '{"function":"initLedger","Args":[""]}'

#echo '####### QUERY ########################'
#sleep 10
#docker exec -e "CORE_PEER_LOCALMSPID=Org1MSP" -e "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp" cli peer chaincode query -o $HYPERLADGER_ORDERER_SERVER -C $CHANNEL -n $APP_NAME -c '{"Args":["queryAllTuna",""]}'


echo DEPLOYED: $APP_NAME
